# Generated by Django 3.2.7 on 2021-09-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SH2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_sh2', models.IntegerField()),
                ('no_sh2_por', models.TextField()),
            ],
            options={
                'db_table': 'sh2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_via', models.IntegerField()),
                ('no_via', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'via',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_ncm', models.IntegerField()),
                ('no_ncm_por', models.TextField()),
                ('sh2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.sh2')),
            ],
            options={
                'db_table': 'ncm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FComex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('cod_unidade', models.IntegerField()),
                ('cod_pais', models.IntegerField()),
                ('sg_uf', models.CharField(max_length=2)),
                ('cod_urf', models.IntegerField()),
                ('vl_quantidade', models.IntegerField()),
                ('vl_peso_kg', models.IntegerField()),
                ('vl_fob', models.IntegerField()),
                ('movimentacao', models.CharField(max_length=2)),
                ('ncm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ncm')),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.via')),
            ],
            options={
                'db_table': 'fcomex',
                'managed': True,
            },
        ),
    ]
